### ISSUE TITLE
Refactor the styles

### ISSUE THREAD

**Issue by AdamSiekierski** [tripleadev/zsktasks-website#3]
Currently, the styles of website are stored inside CSS files and some of the components are made using `styled-components`. We need to refactor all the styling to be made using `styled-components` and create a Theme Provider, so that in the future we could easily create dark theme

**Comment by AdamSiekierski** [comment]
guyz pls someone make this task

**Comment by AleksanderSkubala** [comment]
I've got some time, I can take it

**Comment by AdamSiekierski** [comment]
Done :D
